package lexico;

public enum Token {
	llaveIzq,
        lleveDere,
        corcheteIzq,
        corcheteDere,
        parentisiIzq,
        parentisiDere,
        iint,
        ffloat,
        cchar,
        bbolean,
        igual,
        iif,
        eelse,
        wwhile,
        ddo,
        bbreak,
        puntoYcoma,
        iss,
        or,
        igualIgual,
        menorque,
        mayorque,
        mayorIgual,
        menorIgual,
        suma,
        resta,
        multiplicacion,
        divicion,
        admiracion,
        num,
        real,
        ttrue,
        ffalse,
        id, 
        negacion,
        ERROR,
        _shift,
        _accept,
        _error,
        _fin
      
}
